### ISSUE TITLE
Reboot to payload > hekate

### ISSUE THREAD

**Issue by Skonikol** [Yoti/DoTenNin#1]
Перезагрузка должна быть в гекату, иначе все прелести reboot_payload.bin теряются, если перезагружаться в фузи. Имхо в скрипт нужно добавить подстановку гекаты вместо fusee в reboot_payload.bin

**Comment by Yoti** [comment]
А есть ли реальное подтверждение тому, что сборка работает иначе? Так как согласно [документации](https://github.com/CTCaer/hekate#hekate-global-configuration-keysvalues-when-entry-is-config) **hekate** делает это сам. В моём (комплектном) `hekate_ipl.ini` установлена настройка `updater2p=1`. Если используется свой файл, предлагаю изменить его аналогичным образом.
